### ISSUE TITLE
whats the use of `gulp-wait`

### ISSUE THREAD

**Issue by danny007in** [themesberg/volt-bootstrap-5-dashboard#41]
and y it is necessary

**Comment by zoltanszogyenyi** [comment]
Hey @danny007in.

We use it as a small buffer time between the reading of source files (SASS, HTML, CSS) until the compilation is done. We've had a weird issue where sometimes the compilation wouldn't happen correctly, and this is something that fixed it. But anyway, we want to use Webpack in the future instead of Gulp. Probably for the v2.0.

**Comment by danny007in** [comment]
Take a look, if ur not busy completely https://github.com/ColorlibHQ/AdminLTE/blob/v4-dev/gulpfile.js and https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev
